# Generated by Django 5.0.6 on 2024-07-23 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_profile_portrait_path'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='portrait_path',
            new_name='portrait',
        ),
    ]
