# Generated by Django 5.0.6 on 2024-07-11 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TmpUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email')),
                ('verification_code', models.TextField(max_length=10, verbose_name='verification_code')),
                ('is_verified', models.BooleanField(verbose_name='is_verified')),
            ],
        ),
    ]
