# Generated by Django 5.0.6 on 2024-07-12 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tmpuser',
            name='is_verified',
            field=models.BooleanField(default=False, verbose_name='is_verified'),
        ),
        migrations.AlterField(
            model_name='tmpuser',
            name='verification_code',
            field=models.TextField(blank=True, max_length=10, null=True, verbose_name='verification_code'),
        ),
    ]
