# Generated by Django 5.0.6 on 2024-07-24 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_rename_video_path_video_video_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='videos/cover_images'),
        ),
    ]
