# Generated by Django 5.0.6 on 2024-07-24 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_video_cover_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='cover_image',
            field=models.ImageField(upload_to='videos/cover_images'),
        ),
    ]
